### ISSUE TITLE
trained model on cityscapes

### ISSUE THREAD

**Issue by krishnakanthnakka** [rosinality/ocr-pytorch#4]
Do you mind sharing the trained model on cityscapes?

**Comment by rosinality** [comment]
Hmm I haven't tried this model on cityscapes.

**Comment by krishnakanthnakka** [comment]
do you have any trained model on other datasets? I want to try some experiments to understand effects of contextual dependencies in OCRNet.

**Comment by rosinality** [comment]
I have checkpoints trained on ADE20K: https://drive.google.com/open?id=1xRrAB8dMTL-S7aYK5UrEoyWYWn2B_uhg

**Comment by krishnakanthnakka** [comment]
Thank you:)
